# SPDX-License-Identifier: Apache-2.0
# Modifications Copyright (c) 2026 Junner

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

org.gradle.configuration-cache=false


# Mod Properties
mod_version=1.0.11
maven_group=me.sootysplash
archives_base_name=hero-hitboxes

# Fabric Properties
# check these on https://fabricmc.net/develop

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT

fabric_version=0.156.0+26.2

modmenu_version=20.0.1
cloth_config_version=26.2.155
